changelog:
  sections:
    - title: ":star: New Features"
      labels: ["enhancement"]
    - title: ":lady_beetle: Bug Fixes"
      labels: ["bug", "regression"]
    - title: ":notebook_with_decorative_cover: Documentation"
      labels: ["documentation"]
    - title: ":hammer: Dependency Upgrades"
      labels: ["dependency-upgrade", "dependencies"]
  contributors:
    exclude:
      names: ["dependabot", "d-claassen"]
