name: 'CI'

on:
  push:
    branches:
      - main
  pull_request: null

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }} 
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: 'Quality Control'
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        
      - name: 'Setup Node and node_modules cache'
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
        
      - name: 'Validate composer.json and composer.lock'
        run: 'composer validate --no-check-publish'
        
      - name: 'NPM install'
        run: npm install
        
      - name: 'Composer install'
        run: 'composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader'
        
      - name: 'Check engines'
        run: 'npm run-script check-engines'
        
      - name: 'Check licenses'
        run: 'npm run-script check-licenses'
      
      - name: 'Lint package.json'
        run: 'npm run-script lint:pkg-json'
        
      - name: 'Lint Markdown'
        run: 'npm run-script lint:md:docs'
        
      - name: 'Lint JS'
        run: 'npm run-script lint:js'
        
      - name: 'Lint CSS'
        run: 'npm run-script lint:css'
    
      - name: 'Lint PHP source files'
        run: 'php -l src'
        
      - name: 'Lint PHP test files'
        run: 'php -l tests'
    
      - name: 'Test JS units'
        run: 'npm run-script test:unit -- --coverage'
        
      - name: 'Test PHP units'
        run: 'php vendor/bin/phpunit'
        
      - name: 'Test e2e'
        run: 'npm run-script test:e2e'
      
