name: 'CI'

on:
  push:
    branches:
      - main
  pull_request: null

permissions:
  contents: write

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }} 
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: 'Quality Control'
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
        
      - name: 'Setup Node and node_modules cache'
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
        
      - name: update
        run: composer update phpunit/phpunit
      - name: push
        run: |
          git config --global user.name 'Dennis Claassen'
          git config --global user.email 'd-claassen@users.noreply.github.com'
          git commit -am "Automated Composer update"
          git push origin HEAD:update-composer
        
      - name: 'Validate composer.json and composer.lock'
        run: 'composer validate --no-check-publish'
        
      - name: 'NPM install'
        run: npm install
        
      - name: 'Check engines'
        run: 'npm run-script check-engines'
        
      - name: 'Check licenses'
        run: 'npm run-script check-licenses'
      
      - name: 'Lint package.json'
        run: 'npm run-script lint:pkg-json'
        
      - name: 'Lint Markdown'
        run: 'npm run-script lint:md:docs'
        
      - name: 'Lint JS'
        run: 'npm run-script lint:js'
        
      - name: 'Lint CSS'
        run: 'npm run-script lint:css'
        
      - name: 'Test units'
        run: 'npm run-script test:unit -- --coverage'
        
      - name: 'Test e2e'
        run: 'npm run-script test:e2e'
      
