name: 'CI'

on:
  push:
    branches:
      - main
  pull_request: null

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: 'Quality Control'

    steps:
      - name: Install subversion
        run: sudo apt-get install -y subversion

      - name: 'Checkout'
        uses: actions/checkout@v5

      - name: 'Setup Node and node_modules cache'
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: 'Validate composer.json and composer.lock'
        run: 'composer validate --no-check-publish'
        continue-on-error: true

      - name: 'NPM install'
        run: npm install

      - name: 'Composer install'
        run: 'composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader'

      - name: 'Check engines'
        run: 'npm run-script check-engines'

# Broken.
#      - name: 'Check licenses'
#        run: 'npm run-script check-licenses'

      - name: 'Lint package.json'
        run: 'npm run-script lint:pkg-json'

      - name: 'Lint Markdown'
        run: 'npm run-script lint:md:docs'

      - name: 'Lint JS'
        run: 'npm run-script lint:js'

      - name: 'Lint CSS'
        run: 'npm run-script lint:css'

      - name: 'Lint PHP'
        run: 'composer lint'

      - name: 'PHP code style'
        run: 'composer cs'

      - name: 'Static analysis PHP'
        run: './vendor/bin/phpstan analyze src'

      - name: 'Test JS units'
        run: 'npm run-script test:unit -- --coverage'

      - name: 'build the theme'
        run: 'npm run-script build'

      - name: 'Test PHP units'
        run: 'composer test -- --coverage-text --testdox'

      - name: 'Ditch dev dependencies'
        run: 'composer install --no-dev --prefer-dist --no-progress --no-suggest --optimize-autoloader'

      - name: 'Zip it'
        run: 'npm run-script plugin-zip -- --help'

      - name: 'Archive theme.zip'
        uses: actions/upload-artifact@v5
        with:
          name: 'dennisclaassen2023'
          path: 'dennisclaassen2023.zip'
