name: 'CI'

on:
  push:
    branches:
      - main
  pull_request: null

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }} 
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: 'Quality Control'

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        
      - name: 'Setup Node and node_modules cache'
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: 'Validate composer.json and composer.lock'
        run: 'composer validate --no-check-publish'
        
      - name: 'NPM install'
        run: npm install
        
      - name: 'Composer install'
        run: 'composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader'

# not yet ready for phpunit 10
#      - name: 'Composer install pt 2'
#        run: 'composer require yoast/wp-test-utils --dev'
        
      - name: 'Check engines'
        run: 'npm run-script check-engines'
        
      - name: 'Check licenses'
        run: 'npm run-script check-licenses'
      
      - name: 'Lint package.json'
        run: 'npm run-script lint:pkg-json'
        
      - name: 'Lint Markdown'
        run: 'npm run-script lint:md:docs'
        
      - name: 'Lint JS'
        run: 'npm run-script lint:js'
        
      - name: 'Lint CSS'
        run: 'npm run-script lint:css'
    
      - name: 'Lint PHP'
        run: 'composer lint'
        
      - name: 'PHP code style'
        run: 'composer cs'
        
      - name: 'Test JS units'
        run: 'npm run-script test:unit -- --coverage'

      - name: 'execute rights'
        run: 'chmod +x .github/workflows/install-wp-tests.sh'

      - name: 'Install WordPress'
        shell: bash
        run: '.github/workflows/install-wp-tests.sh wordpress_test root "" 127.0.0.1:3306 latest'

      - name: 'Test PHP units'
        run: 'composer test -- --coverage-text --testdox --testsuite="Mockery Tests"'
        
      - name: 'Test PHP WP units'
        run: 'composer test -- --coverage-text --testdox --testsuite="WordPress context" --bootstrap=/tmp/wordpress-tests-lib/includes/bootstrap.php'

      - name: 'Test e2e'
        run: 'npm run-script test:e2e'

      - name: 'build the theme'
        run: 'npm run-script build'

      - name: 'Zip it'
        run: 'npm run-script plugin-zip -- --help'

      - name: 'Archive theme.zip'
        uses: actions/upload-artifact@v3
        with:
          name: 'dennisclaassen2023'
          path: 'dennisclaassen2023.zip'
