name: 'Release version'

on:
  milestone:
    types: [closed]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: 'Create release with notes'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup Node and node_modules cache'
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: 'NPM install'
        run: npm install
        
      - name: 'Composer install'
        run: 'composer install --no-dev --prefer-dist --no-progress --no-suggest --optimize-autoloader'

      - name: 'Build the theme'
        run: 'npm run-script build'

      - name: 'Zip it'
        run: 'npm run-script plugin-zip -- --help'

      - name: 'Create release notes'
        uses: docker://decathlon/release-notes-generator-action:2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILENAME: Changelog

      - name: Test 1
        run: ls -la

      - name: 'Push the tag (directly)'
        run: |
          git config --global user.name 'Dennis Claassen'
          git config --global user.email 'd-claassen@users.noreply.github.com'
          npm --no-git-tag-version version "${{ github.event.milestone.title }}"
          git add package.json
          sed -i 's/^Version: [0-9].*$/Version: ${{ github.event.milestone.title }}/' style.css
          git add style.css
          git commit -m 'Release version ${{ github.event.milestone.title }}'
          git tag ${{ github.event.milestone.title }}
          git push --follow-tags

      # - name: 'Push the tag'
      #   uses: actions-ecosystem/action-push-tag@v1
      #   with:
      #     tag: ${{ github.event.milestone.title }}

      - name: Test 2
        run: ls -la

      - name: 'Archive theme.zip'
        uses: actions/upload-artifact@v3
        with:
          name: 'dennisclaassen2023'
          path: 'dennisclaassen2023.zip'

      - name: 'Release'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.milestone.title }}
          body_path: 'release_file.md'
          files: 'dennisclaassen2023.zip'
          prerelease: true
