name: 'Release version'

on:
  milestone:
    types: [closed]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: 'Create release with notes'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup Node and node_modules cache'
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: 'NPM install'
        run: npm install
        
      - name: 'Composer install'
        run: 'composer install --no-dev --prefer-dist --no-progress --no-suggest --optimize-autoloader'

      - name: 'Build the theme'
        run: 'npm run-script build'

      - name: 'Zip it'
        run: 'npm run-script plugin-zip -- --help'

      - name: 'Create release notes'
        uses: docker://decathlon/release-notes-generator-action:2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILENAME: Changelog
          
      - name: Test
        run: ls -l

      - name: 'Archive theme.zip'
        uses: actions/upload-artifact@v3
        with:
          name: 'dennisclaassen2023'
          path: 'dennisclaassen2023.zip'

      - name: 'Release'
        uses: softprops/action-gh-release@v1
        with:
          body_path: 'release_file.md'
          files: 'dennisclaassen2023.zip'
          prerelease: true