name: End-to-End Tests

on:
    pull_request:
    push:
        branches:
            - main

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    e2e-playwright:
        name: Playwright - ${{ matrix.part }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                wp_version: ["6.7"]

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - name: NPM install
              run: npm install

            - name: 'Setup PHP'
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php_version }}

            - name: 'Validate composer.json and composer.lock'
              run: 'composer validate --no-check-publish'

            - name: 'NPM install'
              run: npm install

            - name: 'Composer install'
              uses: ramsey/composer-install@v3
              with:
                  dependency-version: ${{ matrix.dependencies_version }}
                  composer-options: '--prefer-dist --no-progress --no-suggest --optimize-autoloader'
 
            #- name: Install Playwright dependencies
            #  run: npx playwright install chromium firefox webkit --with-deps

            - name: Install WordPress and start the server
              run: |
                  npm run wp-env start

            - name: Run the tests
              #env:
              #    PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
              run: npm run test:e2e
